name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr

      - name: Lint
        run: |
          error=0
          for file in $(find upload -type f -name "*.php" ! -path 'upload/system/storage/vendor/*'); do
            php -l -n $file | grep -v "No syntax errors detected" && error=1
          done
          if [ $error -eq 1 ]; then
            echo "Syntax errors were found."
            exit 1
          else
            echo "No syntax errors were detected."
          fi

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/composer/files
            ./.cache
            ./.php-cs-fixer.cache
          key: ${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: OC3.2-PHP${{ matrix.php }}-

      - name: PHPStan
        run: |
          composer require phpstan/phpstan 1.10.57
          ./upload/system/storage/vendor/bin/phpstan analyze --no-progress

      - name: Code style
        run: |
            composer require --dev friendsofphp/php-cs-fixer v3.46.0
            ./upload/system/storage/vendor/bin/php-cs-fixer fix --dry-run --diff --ansi || true
            ./upload/system/storage/vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr
